### ISSUE TITLE
player.game_time might not be updating

### ISSUE THREAD

**Issue by mlandrum22** [cwendt94/espn-api#117]
There's about 13 minutes left in the 2nd quarter of the Titans game and Tannehill's game_time is still 0.

I didn't check it during the Sunday games so I don't know if it's just isolated to this one or not.

**Comment by cwendt94** [comment]
Thanks for letting me know. Looking into it now!

**Comment by cwendt94** [comment]
@mlandrum22 I am remembering that feature now and that is the correct value. It is only used to know if the player has played their game or not. So `0` is either not played/playing and `100` means they have played their game. It can probably be updated to give some percentage so that its a little more informative

**Comment by mlandrum22** [comment]
Ohhh gotcha, thanks! Maybe change the wiki to make it say 0 or 100 until it's updated to show a percent. 0-100 made it sound like it gives a range.

**Comment by cwendt94** [comment]
Yes, I will definitely do that. The wording is misleading on the wiki!

**Comment by cwendt94** [comment]
Closing for now, documentation updated
