### ISSUE TITLE
Get current fantasy week dynamically

### ISSUE THREAD

**Issue by gobo7793** [cwendt94/espn-api#132]
I recently had on my discord bot the problem, that I can't get the fantasy football matchup scores of the current week after the bot wasn't restarted over a week. It seems, that you fetch the `League.current_week` only on creating a league, but I hold the league object permanently in memory. So after the week is over, I can't access the scores of the following week without restarting since you [prevent getting box scores from future weeks](https://github.com/cwendt94/espn-api/blob/master/espn_api/football/league.py#L188).

So would it be possible to fetch the current week dynamically or at least check if the current week is up to date on getting the box scores? (And maybe standings, but didn't check it there)

**Comment by cwendt94** [comment]
The best bet would be to reload the League's data so that everything is up to date (Teams players, standings, current week, etc). Right now I don't have a "public" method to reload the data but you can call `league._fetch_league()` for right now and that will get the latest data. When I have some time I can add a public method and update documentation.

**Comment by cwendt94** [comment]
New league function `league.refresh()` that will get the latest league data. This is in v0.8.2
