### ISSUE TITLE
Fix Team Data Change Working?

### ISSUE THREAD

**Issue by adinwritescode** [cwendt94/espn-api#486]
### Sport

Football

### Summary

Hi,

I've been using this project pretty regularly (~every day) since the season started but got an error just this morning due to the change to team data. I updated to v0.32 which has resolved the error, but I'm seeing a few other things that are making usability difficult, inlcuding

- There seems to be .owner attribute for teams anymore
- Team names are showing as "Unknown Unknown" for all previous years

Thanks!

### Logs/Data

Screenshot of a schedule from 2022:

<img width="266" alt="image" src="https://github.com/cwendt94/espn-api/assets/67563266/a5048a91-9a0b-4697-a2a7-39b0bdf9ef60">

**Comment by cwendt94** [comment]
Thanks for reporting this! Yeah they removed owner names data so I removed it but I think we should still include the owner id. Someone created a PR adding owner id back [here](https://github.com/cwendt94/espn-api/pull/487), so hopefully that will be in soon.

For the Team name, I recently started seeing that as well when some integration tests started failing. I need to look into it but I think they might have updated their previous data to the new team format that they added this year that was fixed in this [PR](https://github.com/cwendt94/espn-api/commit/cc82818bada7bda0e12fb10688943fbb46103bd2#diff-0caa08d87ac7790372e773c0bb16eb97cddba1d80156c4dfd82d692dab0c5847R14)
