### ISSUE TITLE
Two-week playoff rounds not pulling second week

### ISSUE THREAD

**Issue by yayanz** [cwendt94/espn-api#78]
Apologies if I'm just missing something, but my league has two-week playoffs starting week 14/15 and week 15 doesn't seem to be pulling in. Duplicates week 14. Anyone else seeing this?

**Comment by cwendt94** [comment]
Yes, I believe this is a bug. For grabbing scores I filter off of matchup period by the current week and because the two-week playoff is still considered the same matchup period it doesn’t update for the next week.

Espn has a scoringPeriod which I believe can be used for the multiple week matchups that would show the correct information. I need to do some investigation to see if there is a way to know if the current matchup is multiple weeks.
